### PR TITLE
Updated terms and privacy policy

### PR DESCRIPTION
**Pull request by devmilind**
Updated terms and privacy text.

### CODE REVIEW

**Comment by devmilind** [comment]
;rfr @jcandeli

**Review by mark-kawakami-zefr — APPROVED** [review]

**Comment by mark-kawakami-zefr** [comment]
LGTM, RFT it to whomever

**Comment by devmilind** [comment]
;rft @cjduar

**Comment by cjduar** [comment]
Good to go

:shipit: @devmilind

**Pull request merged**
